site_name: Dokumentation von André Kloster
site_description: Die IT Dokumentation von André Kloster
site_author: André Kloster
repo_url: https://github.com/andrekloster/boilerplate/
repo_name: andrekloster/boilerplate
theme:
    name: 'material'
    language: de
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - navigation.indexes
        - content.code.copy
    plugins:
        - search:
            lang: de
markdown_extensions:
    - 'admonition'
    - 'pymdownx.highlight'
    - 'pymdownx.keys'
    - 'pymdownx.superfences'
    - pymdownx.tabbed:
        alternate_style: true
    - 'attr_list'
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - 'md_in_html'
nav:
    - Home:
        - 'index.md'
    - Server:
        - 'server/cluster.md'
        - 'server/drbd.md'
    - IaC:
        - Puppet:
            - 'iac/puppet/create_puppet_server.md'
            - 'iac/puppet/register_client.md'
            - 'iac/puppet/icinga_ntfy.md'
        - Ansible:
            - 'iac/ansible/dns.md'
    - Container & Virtualisierungen:
        - LXC:
            - 'container/lxc/preparation.md'
            - 'container/lxc/unprivileged_container.md'
            - 'container/lxc/privileged_container.md'
            - 'container/lxc/raspberrypi.md'
            - 'container/lxc/create_with_proxy.md'
        - Xen:
            - 'virt/xen.md'
    - Datenbanken:
        - 'databases/etcd.md'
        - 'databases/postgresql_patroni.md'
        - 'databases/mysql_innodb.md'
        - 'databases/mongodb.md'
    - Monitoring:
        - 'monitoring/icinga.md'
    - PKI:
        - 'pki/mini_pki.md'
