site_name: Dokumentation
theme:
  name: material
  language: de


markdown_extensions:
  - 'admonition'
  - 'pymdownx.highlight'
  - 'pymdownx.keys'
  - 'pymdownx.superfences'
  - 'pymdownx.tabbed'

nav:
  - Home: 'index.md'
  - DNS: 'dns.md'

